title: In development
author: Raúl Benito
email: erre.benito@gmail.com
description: >-
  Personal projects and random musings of a full-stack developer
domain: errebenito.github.io
baseurl: ""
url: https://errebenito.github.io
github_username:  errebenito
linkedin_username: errebenito
# Build settings
theme: minima
plugins:
  - jekyll-feed
